### ISSUE TITLE
Document :memory: database connection issues, perhaps enforce a single connection.

### ISSUE THREAD

**Issue by AlexMax** [mattn/go-sqlite3#309] opened 2016-06-08 00:54 UTC
I encountered a strange bug with an in-memory database where I was accidentally leaving transactions uncommitted.  To my surprise, it turns out that every new connection creates a brand-spanking new in-memory database, which meant that I wasn't running queries against the database I thought I was, but a blank database, resulting in some perplexing errors involving missing data that I was sure was actually there.

I eventually fixed the bug by eliminating an extraneous Begin() that had crept into my code, but I can't imagine a situation where "please run this query against a fresh database" would be desirable.  Could this behavior at the very least be documented somewhere?  It'd be nice if perhaps the driver could somehow limit the number of concurrent connections to in-memory databases to one, but you might still need to document this behavior so people don't get confused when they run into a deadlock caused by connection that was left open.

**Comment by dgsb** [comment] 2016-09-16 07:27
Hello @AlexMax, did you observed any behaviour different from the ones described here: https://www.sqlite.org/inmemorydb.html ?

**Comment by fgrosse** [comment] 2016-11-15 08:47
This seems to be a duplicate of #204 or at the very least it is related.

**Closed** 2017-01-27 00:02 UTC
