### ISSUE TITLE
Dependabot suddenly pushing v2.0.3

### ISSUE THREAD

**Issue by romainmenke** [mattn/go-sqlite3#997] opened 2022-01-11 06:54 UTC
see : https://github.com/mrhenry/web-tests/pull/273

context : 

> Latest stable version is v1.14 or later, not v2.
>NOTE: The increase to v2 was an accident. There were no major changes or features.

I have no idea why dependabot suddenly pushes v2.0.3 but wanted you to know that this happens.
I couldn't find any changes here that might have triggered this so they probably changed some logic.

You can close this after reading :)

**Comment by sagikazarmark** [comment] 2022-01-11 07:15
Duplicate of #975

**Comment by romainmenke** [comment] 2022-01-11 07:21
I don't think it's the same issue although it probably has the same cause.
I think dependabot is doing something weird here.

**Closed** 2022-05-19 20:53 UTC
