### ISSUE TITLE
go-sqlite3 still using built-in copy despite libsqlite3 tag

### ISSUE THREAD

**Issue by stgraber** [mattn/go-sqlite3#330] opened 2016-09-21 17:23 UTC
Building with -tags libsqlite3, while it does seem to be using the sqlite3.h from the system, still appears to be using the built-in copy of the actual code rather than linking against the system library.
```
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ go build -tags libsqlite3 _example/simple/simple.go
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ ldd simple | grep sqlite
```

Now if I actually remove the embedded copy and try again (no other changes):
```
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ rm sqlite3-binding.*
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ go build -tags libsqlite3 _example/simple/simple.go
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ ldd simple | grep sqlite
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f8ba57ea000)
```

Any idea what's going on?

**Comment by leehambley** [comment] 2016-09-23 08:45
I think this is a duplicate of https://github.com/mattn/go-sqlite3/issues/318#issue-167219373 having reviewed some of the other issues related to `-tag libsqlite3`

**Comment by mattn** [comment] 2016-09-27 02:22
This is related on this. https://github.com/mattn/go-sqlite3/pull/294

**Closed** 2016-10-28 08:48 UTC
