### ISSUE TITLE
Warning and note in sqlite3-binding.c

### ISSUE THREAD

**Issue by KrisCarr** [mattn/go-sqlite3#803] opened 2020-04-14 17:52 UTC
Every time my application starts or tests are run I get the following in my output:

```
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

I can get round this by adding `-w` to the CFLAGS option inside sqlite3.go 

Is there a better way to get rid of this warning and note?

I am running on Fedora 32 x86_64

**Comment by KrisCarr** [comment] 2020-04-14 18:14
I have added `-Wno-return-local-addr"` to my environment variables in .bashrc which has got rid of all that mess for the time being.
```
export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"
```

**Comment by james-d-elliott** [comment] 2020-05-07 23:15
A user of a package I maintain complained about the same thing. If you're able I'm interested in your gcc, glibc, and libsqlite3 versions.

**Comment by pgnd** [comment] 2020-05-08 03:22
with
```
sqlite3 --version
	3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
```

build with gcc10
```
	echo $CC $CXX $CPP
		/usr/bin/gcc-10 /usr/bin/g++-10 /usr/bin/cpp-10
	$CC --version
		gcc-10 (SUSE Linux) 10.1.1 20200507 [revision dd38686d9c810cecbaa80bb82ed91caaa58ad635]
	go build github.com/mattn/go-sqlite3
		# github.com/mattn/go-sqlite3
		sqlite3-binding.c: In function ‘sqlite3SelectNew’:
		sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
		128049 |   return pNew;
		       |          ^~~~
		sqlite3-binding.c:128009:10: note: declared here
		128009 |   Select standin;
		       |          ^~~~~~~
```

and, build with gcc9
```
	echo $CC $CXX $CPP
		/usr/bin/gcc-9 /usr/bin/g++-9 /usr/bin/cpp-9
	$CC --version
		gcc-9 (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]
	go build github.com/mattn/go-sqlite3

=====> NO SQLITE3 ERROR <====
```

**Comment by james-d-elliott** [comment] 2020-05-08 03:33
Yeah, looks like a gcc 10 issue, 9.3 works fine. Same problem with our user. It's likely the issue lies with libsqlite3-0 3.31.1 and gcc 10.x. Either a new warning being detected or a problem with 10.x - a lot of issues were resolved in 10.1 marked as regressions introduced between 9.3 and 10.0 (~700) so it could be that.

**Comment by pgnd** [comment] 2020-05-08 03:38
fyi, with
```
sqlite3 --version
	3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
```

build with gcc10
```
	echo $CC $CXX $CPP
		/usr/bin/gcc-10 /usr/bin/g++-10 /usr/bin/cpp-10
	$CC --version
		gcc (SUSE Linux) 10.0.1 20200501 (prerelease) [revision 2aaa1dc3c87372fd55c1c33aa7a9612c4e5179e8]
	git clean -xfd; git reset --hard; git pull
	go build github.com/mattn/go-sqlite3
		# github.com/mattn/go-sqlite3
		sqlite3-binding.c: In function ‘sqlite3SelectNew’:
		sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
		128049 |   return pNew;
		       |          ^~~~
		sqlite3-binding.c:128009:10: note: declared here
		128009 |   Select standin;
		       |          ^~~~~~~
```

and, build with gcc9
```
	echo $CC $CXX $CPP
		/usr/bin/gcc-9 /usr/bin/g++-9 /usr/bin/cpp-9
	$CC --version
		gcc-9 (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]
	git clean -xfd; git reset --hard; git pull
	go build github.com/mattn/go-sqlite3

=====> NO SQLITE3 ERROR <====
```

**Comment by pgnd** [comment] 2020-05-08 03:58
looks likely
```
git clone https://github.com/sqlite/sqlite.git
cd sqlite
git checkout version-3.31.1
gcc --version
	gcc (SUSE Linux) 10.1.1 20200507 [revision dd38686d9c810cecbaa80bb82ed91caaa58ad635]
./configure
make
	...
	libtool: link: /usr/bin/gcc-10 -O3 -Wall -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native -D_FORTIFY_SOURCE=2 -O3 -Wall -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native -DSQLITE_OS_UNIX=1 -I. -I/usr/local/src/sqlite/src -I/usr/local/src/sqlite/ext/rtree -I/usr/local/src/sqlite/ext/icu -I/usr/local/src/sqlite/ext/fts3 -I/usr/local/src/sqlite/ext/async -I/usr/local/src/sqlite/ext/session -I/usr/local/src/sqlite/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_HAVE_ZLIB=1 -DHAVE_READLINE=0 -DHAVE_EDITLINE=1 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_DESERIALIZE -o sqlite3 shell.c sqlite3.c  -ledit -ldl -lz -lpthread -Wl,-rpath -Wl,/usr/local/sqlite-gcc10-test/lib64
	In function 'zipfileComparePath',
	    inlined from 'zipfileUpdate' at shell.c:5784:11:
	shell.c:5656:17: warning: '__builtin_memcmp_eq' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
	 5656 |   if( nA==nB && memcmp(zA, zB, nA)==0 ) return 0;
	      |                 ^~~~~~~~~~~~~~~~~~
	sqlite3.c: In function ‘sqlite3SelectNew’:
	sqlite3.c:128048:10: warning: function may return address of local variable [-Wreturn-local-addr]
	128048 |   return pNew;
	       |          ^~~~
	sqlite3.c:128008:10: note: declared here
	128008 |   Select standin;
	       |          ^~~~~~~
	sqlite3.c:128008:10: note: declared here
	sqlite3.c: In function 'sqlite3SelectNew':
	sqlite3.c:128048:10: warning: function may return address of local variable [-Wreturn-local-addr]
	128048 |   return pNew;
	       |          ^~~~
	sqlite3.c:128008:10: note: declared here
	128008 |   Select standin;
	       |          ^~~~~~~
	sqlite3.c:128008:10: note: declared here
	...
```

**Comment by rbucker** [comment] 2020-05-15 16:04
In my case...

```
$ go get -u -v github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

ClearLinux version:

```
$ swupd check-update 
Current OS version: 33100
Latest server version: 33100
There are no updates available
```

GCC Version

```
$ gcc --version
gcc (Clear Linux OS for Intel Architecture) 10.1.1 20200513 releases/gcc-10.1.0-36-gf2b77b928a
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [comment] 2020-05-18 02:13
windows 10 x64 2004 has the same issue

**Comment by james-d-elliott** [comment] 2020-05-18 03:23
This is an upstream bug with libsqlite3, not sure where their bug tracker is.

**Comment by subpop** [comment] 2020-05-18 13:26
> This is an upstream bug with libsqlite3, not sure where their bug tracker is.

https://www3.sqlite.org/cgi/src/ticket

**Comment by LawnGnome** [comment] 2020-05-27 21:00
There's a discussion [on the SQLite Forum](https://sqlite.org/forum/forumpost/e39020f82d7d510ea4d4a08ae370ca8df061c8b91884c82fda4897853faa2096) about this issue, including a candidate patch.

**Comment by payloadartist** [comment] 2021-03-03 07:48
Facing this issue with GoORM, which uses this. Any workarounds?

**Comment by edo1** [comment] 2021-04-29 17:46
fixed in sqlite3 release 3.33, so go-sqlite3 1.14.1 and later doesn't have this issue 

P. S. actual go-sqlite3 release is 1.14.7, not 2.0.x

**Comment by qweccc** [comment] 2021-05-06 01:21
> export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"

itz work

**Comment by pablodz** [comment] 2022-02-07 21:22
> Don't disable these warnings, people. You **want** to see them.
> 
> It's like seeing a small fire, closing your eyes and pretending it's not there!

You have described the whole tech industry

![image](https://user-images.githubusercontent.com/28235457/152874065-68bd2ce8-c7a0-4bf1-b564-86615fba2128.png)

**Comment by shalota1** [comment] 2022-08-11 20:44
Hello I am facing the same problem while I try to install gophish. 
I use sudo go install github.com/gophish/gophish@latest ( Because get is deprecated from go dependecies and should add the value @latest or version.
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
This is the error I get. Please is there any workaround?

**Comment by rittneje** [comment] 2022-08-11 20:50
@shalota1 gophish is using v2.0.3 of this library, which is quite old. You will need to ask the maintainer to upgrade to the latest version (v1.14.14) and try that.

**Comment by PetengDedet** [comment] 2022-09-17 05:14
For Windows user 
```shell
go env -w CGO_CFLAGS="-g -O2 -Wno-return-local-addr"
```

**Comment by mvikrammenon** [comment] 2023-04-26 05:23
> @shalota1 gophish is using v2.0.3 of this library, which is quite old. You will need to ask the maintainer to upgrade to the latest version (v1.14.14) and try that.

Thanks for pointing it out. Tried `go get github.com/mattn/go-sqlite3@v1.14.16` and that updated the few dependencies. Able to build successfully in my Amazon Linux box.
Have raised a PR with fix. https://github.com/gophish/gophish/pull/2848

**Comment by rytcnt** [comment] 2023-05-10 19:48
> > @shalota1 gophish is using v2.0.3 of this library, which is quite old. You will need to ask the maintainer to upgrade to the latest version (v1.14.14) and try that.
> 
> Thanks for pointing it out. Tried `go get github.com/mattn/go-sqlite3@v1.14.16` and that updated few dependencies. Able to build successfully in my Amazon Linux box. Have raised a PR with fix. [gophish/gophish#2848](https://github.com/gophish/gophish/pull/2848)

Thanks - I was able to use your proposed fixes to the go.mod and go.sum files, after doing a `git clone https://github.com/gophish/gophish.git` then a go build in the directory once the two files were modified. For some reason the go get command didn't work, nor did the go install commands.

**Comment by rittneje** [comment] 2024-03-03 05:11
Closing because I believe this issue has long since been fixed in SQLite itself.

**Closed by rittneje** 2024-03-03 05:11 UTC
