### ISSUE TITLE
Problem with unstable  go-sqlite3 version - 2.0.3

### ISSUE THREAD

**Issue by Shriram-RP** [mattn/go-sqlite3#975] opened 2021-10-22 11:36 UTC
Hi,

We at the platform team of razorpay internally use [bulk-insert](https://github.com/t-tiger/gorm-bulk-insert) which internally uses `github.com/jinzhu/gorm v1.9.12` and creates an indirect dependency on github.com/mattn/go-sqlite3 v2.0.3.

Reference :- https://github.com/t-tiger/gorm-bulk-insert/blob/master/go.mod#L14

Now, this setup was working fine for us till last week and suddenly we had a failure in our docker build for github actions citing 
`github.com/mattn/go-sqlite3@v2.0.3+incompatible: unknown revision v2.0.3`

We also saw one of your issues where you mentioned versions 2.0+ were unstable - [issue](https://github.com/mattn/go-sqlite3/issues/755)

Did you stop supporting 2.0.3 version suddenly in the last 7-10 days. We were wondering what caused the breakage of the build from our side. It would be helpful if you could throw some light on this issue.

Thanks,
Shriram

**Comment by shaswa** [comment] 2021-10-31 08:55
One way to fix this is adding the below code to the go.mod file
`exclude github.com/mattn/go-sqlite3 v2.0.3+incompatible 
`

**Comment by delonleo** [comment] 2021-11-03 00:36
any fix ?

**Comment by mattn** [comment] 2021-11-03 01:18
This is not an issue of go-sqlite3. v2 was an accident as written in  README.md

> NOTE: The increase to v2 was an accident. There were no major changes or features.

**Comment by protosam** [comment] 2021-11-03 02:52
@mattn I wonder if this would be a reason to use a retraction and just retag v2: https://golang.org/ref/mod#go-mod-file-retract

The impact of this is a bit broad. Large projects seem to have been impacted by this as well as small random odds and ends. Notice that `tekton/cli` was affected when I was trying to import it into my project. Also searching my cache I see `gorm` managed to get a commit with a v2 tag.

Can't imagine what else this might have landed in. A retraction seems like it would prevent tons of people from having to stuff `exclude` and `replace` into their module files, if I understand the mechanics of it correctly. 

---

```
[protosam@nullhost]$ go mod init placebo
go: creating new go.mod: module placebo
[protosam@nullhost]$ go get github.com/tektoncd/cli@v0.21.0
go get: github.com/tektoncd/cli@v0.9.0 updating to
	github.com/tektoncd/cli@v0.21.0 requires
	github.com/tektoncd/hub/api@v0.0.0-20210922050526-aa589697cb58 requires
	github.com/go-testfixtures/testfixtures/v3@v3.2.0 requires
	github.com/mattn/go-sqlite3@v2.0.2+incompatible: reading github.com/mattn/go-sqlite3/go.mod at revision v2.0.2: unknown revision v2.0.2
```

```
[protosam@nullhost]$ grep -ri 'mattn/go-sqlite3 v2' ~/go/pkg/mod/cache
~/go/pkg/mod/cache/download/github.com/go-testfixtures/testfixtures/v3/@v/v3.2.0.mod:	github.com/mattn/go-sqlite3 v2.0.2+incompatible
~/go/pkg/mod/cache/download/github.com/jinzhu/gorm/@v/v1.9.12.mod:	github.com/mattn/go-sqlite3 v2.0.1+incompatible
```

**Comment by mattn** [comment] 2021-11-03 02:58
If once you clean module cache on your environment, vertion 1.14 shold be used in next time.

**Comment by protosam** [comment] 2021-11-03 03:23
That's not the case. People will be stumbling onto this for a while. `go-sqlite3` is a very wide spread dependency and get added into other projects during both manual and automated tasks. 

Commits like [this](https://github.com/go-testfixtures/testfixtures/blob/9d9d4eea09fd56ea1e90e951f4d02a2032718394/go.mod#L8) and [this](https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/go.mod#L12) are actively referenced in projects today.

There are [39,000](https://github.com/search?l=Text&q=%22v2.0.1%2Bincompatible%22+%22mattn%22+%22go-sqlite3%22&type=Code) files that come up with I search to get an idea of how wide spread this is.

**Comment by rittneje** [comment] 2021-11-03 03:50
@protosam From what I understand, retracting the v2 tags won't resolve any of the existing issues. It just stops the issue from continuing the grow. If I have a dependency on some other module that in turn has a dependency on one of the broken v2 tags of this library, then go mod will still attempt to download that version. And unless you are using proxy.golang.org (or similar), it will fail. The only time retraction matters is when someone is explicitly upgrading their dependencies.

In other words, even if a retraction is published, someone would still have to go to every one of the broken dependents and fix their go.mod to reference a valid release. Then all affected developers have to go and update to the newer versions of these modules. 

@mattn I'm guessing the reason this just become an issue recently is because the v2 tags were deleted from this repo. Is that correct? If so, would you be able to re-create them for the same commits? That way people using "direct" at least won't get failed builds. (This is orthogonal to retracting the v2 releases.)

**Comment by mattn** [comment] 2021-11-03 06:32
Anyone know which commit should i tag ?

**Comment by protosam** [comment] 2021-11-03 06:45
@mattn I'm looking into this.

**Comment by protosam** [comment] 2021-11-03 07:17
Google had them cached in sum.golang.org and also they're still listed at [pkg.go.dev](https://pkg.go.dev/github.com/mattn/go-sqlite3@v2.0.0+incompatible?tab=versions).

[v2.0.0+incompatible](https://sum.golang.org/lookup/github.com/mattn/go-sqlite3@v2.0.0+incompatible)
[v2.0.1+incompatible](https://sum.golang.org/lookup/github.com/mattn/go-sqlite3@v2.0.1+incompatible)
[v2.0.2+incompatible](https://sum.golang.org/lookup/github.com/mattn/go-sqlite3@v2.0.2+incompatible)
[v2.0.3+incompatible](https://sum.golang.org/lookup/github.com/mattn/go-sqlite3@v2.0.3+incompatible)

I'm actually a bit confused on the serialization. Saying what I got in case someone else is able to [understand deserializing this faster than I can](https://cs.opensource.google/go/x/mod/+/refs/tags/v0.5.1:sumdb/dirhash/hash.go).

**Comment by mattn** [comment] 2021-11-03 07:53
v2.0.0 was not a tag. It was branch name.

v2.0.1
https://web.archive.org/web/20201202062638/https://github.com/mattn/go-sqlite3/releases/tag/v2.0.1
590d44c02bca83987d23f6eab75e6d0ddf95f644

v2.0.2
https://web.archive.org/web/20201202062638/https://github.com/mattn/go-sqlite3/releases/tag/v2.0.2
53cff3fcebd1e177d04129dc131523635bc45d3d

v2.0.3
https://web.archive.org/web/20201202060439/https://github.com/mattn/go-sqlite3/releases/tag/v2.0.3
9bdaffc12bf8be15afceb51bb60851edd4afdff5

v2.0.4
https://web.archive.org/web/20201202060440/https://github.com/mattn/go-sqlite3/releases/tag/v2.0.4
db4c9426f851c76327db11e1b5301e520e0e048b

v2.0.5
https://web.archive.org/web/20201202060440/https://github.com/mattn/go-sqlite3/releases/tag/v2.0.5
db4c9426f851c76327db11e1b5301e520e0e048b

v2.0.6
https://web.archive.org/web/20201202060441/https://github.com/mattn/go-sqlite3/releases/tag/v2.0.6
baaf8a978416040e7f2d00ac36e345098d0588d8

**Comment by mattn** [comment] 2021-11-03 07:56
Should all tags be restored?

**Comment by mattn** [comment] 2021-11-03 08:00
I restored older v2.0.X tags. How goes good?

**Comment by mattn** [comment] 2021-11-03 08:05
So you (who used v2.0.X) should modify go.mod to switch v1.4.X.

```
require github.com/mattn/go-sqlite3 v1.14.9
```

**Comment by protosam** [comment] 2021-11-03 09:53
The thousands of forks and archive.org are pretty useful, these commits look good to me and below I've tested them. They work as I expect. 

I did some additional testing to see how the retraction will work. I don't think it works against legacy versioning. Ideally if it worked, we would be capable of getting a message out to the end users so they know they're using bad versions and later these versions can be gracefully claimed for reuse.

No idea where to go with that discovery though. =/

So `v2.0.0`, `v2.0.1`, `v2.0.2`, and `v2.0.3` work because the `+incompatible` tag and there is not a `go.mod` file (legacy versioning).

Tags `v2.0.4`, `v2.0.5`, and `v2.0.6` do not seem to be needed. These have `go.mod` versioning and yield errors that people would have to do more work than necessary to work around. They also don't show up in sum.golang.org and are not listed on pkg.go.dev. Seems likely that no one would miss these tags. This leads me to believe they've not been in use.

---

Started with an empty project and tested getting a module that has a lower dependent  that requires `v2.0.2`.
```
[protosam@nullhost]$ go mod init placebo
go: creating new go.mod: module placebo

[protosam@nullhost]$ go get github.com/tektoncd/cli@v0.21.0
go get: added github.com/tektoncd/cli v0.21.0

[protosam@nullhost]$ go mod verify
all modules verified
```

Below I tested against `v2.0.0` - `v2.0.6`
```
[protosam@nullhost]$ go mod download github.com/mattn/go-sqlite3@v2.0.0+incompatible
[protosam@nullhost]$ go mod tidy

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.0+incompatible
go get: upgraded github.com/mattn/go-sqlite3 v1.14.9 => v2.0.0+incompatible

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.1+incompatible
go get: upgraded github.com/mattn/go-sqlite3 v2.0.0+incompatible => v2.0.1+incompatible

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.2+incompatible
go get: upgraded github.com/mattn/go-sqlite3 v2.0.1+incompatible => v2.0.2+incompatible

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.3+incompatible
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
go get: upgraded github.com/mattn/go-sqlite3 v2.0.2+incompatible => v2.0.3+incompatible

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.4+incompatible
go get: github.com/mattn/go-sqlite3@v2.0.4+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.4
go get: github.com/mattn/go-sqlite3@v2.0.4: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.5
go get: github.com/mattn/go-sqlite3@v2.0.5: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

[protosam@nullhost]$ go get github.com/mattn/go-sqlite3@v2.0.6
go get: github.com/mattn/go-sqlite3@v2.0.6: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

```

**Comment by sagikazarmark** [comment] 2022-01-11 07:25
@mattn I'd probably pin this issue while it's affecting people otherwise they are going to ooen new ones as they rarely look at slightly older issues.

I'd probably reach out to the Go team at this point to see if they have any ideas to stop the spread and fix the problem (eg. remove these entries from sumdb? Dunno if that's possible/good idea)

Retracting would probably mean that you can't use these tags in the future.

**Comment by mattn** [comment] 2022-01-11 07:53
This issue is already reported to Go team. https://github.com/golang/go/issues/35732

**Comment by sagikazarmark** [comment] 2022-01-11 09:44
@mattn as far as I can tell that issue was closed with working as intended. I was rather suggesting to contact them about this specific case, hoping that they could remove the offending entries from the sumdb/proxy.

**Comment by itmecho** [comment] 2022-05-06 13:59
> One way to fix this is adding the below code to the go.mod file `exclude github.com/mattn/go-sqlite3 v2.0.3+incompatible `

Thank you! This fixed my problem. When I ran `go get github.com/mattn/go-sqlite3@v1.14.12`, it downgraded another library I'm using (`ory/fosite`) from `0.40.2` to `0.35.1`. I then added this line to my `go.mod` and ran `go get github.com/ory/fosite@v0.40.2`. This upgraded the package without upgrading `go-sqlite3` to the bad version.

**Comment by kvtb** [comment] 2022-09-12 23:38
> I restored older v2.0.X tags. How goes good?

The tags are disappeared again :(

**Comment by mattn** [comment] 2022-09-12 23:51
The 2.0.X was retracted.

https://pkg.go.dev/github.com/mattn/go-sqlite3?tab=versions

**Closed** 2022-09-12 23:56 UTC

**Comment by rittneje** [comment] 2022-09-13 01:04
@mattn Even though you retracted those versions, those tags should never be deleted, so that people can continue to download their dependencies, including for older versions of their projects.

**Comment by mattn** [comment] 2022-09-13 01:20
@rittneje Yes. My understanding is that once people manually revert to 1.4.X, they will not be upgraded thereafter since 2.X was retracted. I believe this is a problem that cannot be recovered automatically.

**Comment by rittneje** [comment] 2022-09-13 02:04
My point is that deleting those v2 tags breaks people's builds so we should not do that. We can only strongly discourage their use going forward (which the retraction helps).

**Comment by mattn** [comment] 2022-09-13 02:23
I have no plans to release v2 any more.

**Comment by rittneje** [comment] 2022-09-13 02:30
But those tags were already released. So there are other libraries and projects that reference them. By deleting them, those versions cannot be built properly anymore (without using a Go module proxy), which was the original stated issue. We can tell people not to use v2 in new versions of their code anymore, but we should not cause the older/existing versions to break.

**Comment by mattn** [comment] 2022-09-13 02:51
v2 was an accidental release because the Go mod incorrectly identified the branch name as a tag. https://github.com/mattn/go-sqlite3/pull/998 is a PR to add retract as a way to fix these problems.

https://github.com/mattn/go-sqlite3/pull/998

**Comment by rittneje** [comment] 2022-09-13 03:01
Retract doesn't really "fix" the problem per se. In fact, the problem is not really fixable in the way you are hoping. Once a version has been released, it should not be deleted. The retraction fixes some latent issues with fetching/upgrading via `go get github.com/mattn/go-sqlite3@latest`. However, if a project already references, say, `v2.0.3` in its go.sum file, the retraction does not (and should not) interfere with that.

Typically people are using the default Go module proxy at proxy.golang.org. By design, this proxy does not allow versions to be deleted, so that you have eternal build reproducibility. This is an important feature for most people, as they expect all previous versions of their code to always work.

However, in the event that you are not using a proxy (`GOPROXY=off`) then it instead relies on the GitHub tag still existing. It is for this reason that the tags of this repo should be preserved.

My understanding is there were two issues in the history of this repo. The first is the existence of a branch named `v2.0.0`, which, due to an unfortunate bug in `go mod`, was misinterpreted as a release version. The second is a bunch of actual tags (`v2.0.1`, `v2.0.2`, etc.) that were released in error.

**Comment by mattn** [comment] 2022-09-13 03:22
Yes, so I added note in README. https://github.com/mattn/go-sqlite3#go-sqlite3

I have not released v2 in other projects because I do not break compatibility. I also don't want to make it a hassle for the user. Fortunately, as far as I can see, many people still have v1. Because the transition to v2 and beyond is not automatic. So I decided to save the v1 users instead of the v2 users. Do you still think we should release v2.1.X or v3?

BTW, go get with fresh go.mod always get 1.4.X.

![image](https://user-images.githubusercontent.com/10111/189799396-767508c2-49c4-4ad6-bc18-4df2fab74429.png)

**Comment by rittneje** [comment] 2022-09-13 03:29
> Do you still think we should release v2.1.X or v3?

I think you should continue releasing v1.X.Y, as you have been. (In the event you do decide to make breaking changes, going to v3 is probably best to have a clean break from v2.) However, the v2 tags that were already published before should continue to exist indefinitely, you just won't be releasing any _new_ v2.X.Y tags.

> BTW, go get with fresh go.mod always get 1.4.X.

Yes this is due to fixes in `go mod` itself as well as the retraction you did. But if you specifically mention v2.0.3 in your go.mod then it works despite the retraction.

**Comment by mattn** [comment] 2022-09-13 03:42
I figured that leaving the v2 tag could be confusing to new users.

>Yes this is due to fixes in go mod itself as well as the retraction you did. But if you specifically mention v2.0.3 in your go.mod then it works despite the retraction.

Yes, it's same with my understanding. Thanks.

**Comment by kvtb** [comment] 2022-09-14 23:24
> The 2.0.X was retracted.
> 
> https://pkg.go.dev/github.com/mattn/go-sqlite3?tab=versions
> 
> You may have already had go-sqlite3 version 2.0.X. Please update manually to 1.4.X.

Indeed, I can update **my** code, but there are tons of 3rd party libs which require go-sqlite v2.x.x
Should I fork them all ?

**Comment by kvtb** [comment] 2022-09-14 23:26
I see that `v`2 was released by mistake and having legacy `v2` and ongoing `v1` is confusing.
But it seems that in order to fix that mistake you should keep `v1` and `v2` frozen and continue development as `v3`

**Comment by ntsd** [comment] 2022-09-21 09:54
I got the same problem but after I did `go env -w GOPROXY="https://proxy.golang.org,direct"` now it can download.

**Comment by drgrib** [comment] 2022-12-27 21:45
@mattn Deleting the v2.0.3 broke code that I hadn't needed to touch for years. Now when I try to use v1.14.9 I get this error for that code that worked fine before:
```
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

None of the logic I wrote works anymore and it used to. I just get empty values when I query now. How do I fix this?
https://github.com/drgrib/alfred-bear/blob/master/db/db.go#L172

**Comment by rittneje** [comment] 2022-12-27 22:17
@drgrib Are you getting an error, or an empty result set? How specifically are you compiling and executing your code? Have you tried with the latest release (1.14.16)? Also, what does `go env` say?

#855 is not fixable as the Go toolchain does not support that mode of operation. You must compile with `CGO_ENABLED=1` every time.

**Comment by drgrib** [comment] 2022-12-27 22:43
I guess I'm technically not getting an error, just that message when I run along with empty result sets.

Here is my `go env` for a private test project which I am just running with `go run`

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/credford/Library/Caches/go-build"
GOENV="/Users/credford/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/credford/Drive/Files/go/pkg/mod"
GONOPROXY="github.com/drgrib/global_go,github.com/drgrib/settings,github.com/drgrib/global_go118"
GONOSUMDB="github.com/drgrib/global_go,github.com/drgrib/settings,github.com/drgrib/global_go118"
GOOS="darwin"
GOPATH="/Users/credford/Drive/Files/go"
GOPRIVATE="github.com/drgrib/global_go,github.com/drgrib/settings,github.com/drgrib/global_go118"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/credford/Drive/Files/go/src/github.com/drgrib/global_go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f1/p6wb36jd1tl2hnn__v1dv2qr00zzr4/T/go-build2064737576=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

The main file looks like this:

``` golang
package main

import (
	"fmt"

	"github.com/drgrib/global_go/mac/bear"
)

func main() {
	fmt.Println(bear.NoteExistsByTitle("testify"))
}
```

The imported file looks like this:
``` golang
package bear

import (
	"database/sql"
	"fmt"
	"strings"

	"github.com/mattn/go-sqlite3"
	"github.com/pkg/errors"

	"github.com/drgrib/global_go/comp"
)

const (
	DbPath = "~/Library/Group Containers/9K33E3U3T4.net.shinyfrog.bear/Application Data/database.sqlite"

	TitleKey  = "ZTITLE"
	TextKey   = "ZTEXT"
	TagsKey   = "group_concat(tag.ZTITLE)"
	NoteIDKey = "ZUNIQUEIDENTIFIER"

	NOTE_BY_TITLE = `
SELECT DISTINCT
	note.ZUNIQUEIDENTIFIER, note.ZTITLE
FROM
	ZSFNOTE note
WHERE
	note.ZARCHIVED=0
	AND note.ZTRASHED=0
	AND note.ZTEXT IS NOT NULL
	AND utflower(note.ZTITLE) LIKE utflower('%'||$1||'%')
ORDER BY case when utflower(note.ZTITLE) LIKE utflower('%'||$1||'%') then 0 else 1 end, note.ZMODIFICATIONDATE DESC
LIMIT 1
`

	createTemplate = "open bear://x-callback-url/create?title=%s&text=%s&show_window=yes&new_window=yes&edit=yes"
	openTemplate   = "open bear://x-callback-url/open-note?title=%s&show_window=yes&new_window=yes"
)

var (
	bearDB *LiteDB
)

// Only init bearDB if needed for a query so this package stays lightweight
// for other use cases.
func initBearDBIfNil() error {
	if bearDB == nil {
		var err error
		bearDB, err = NewBearDB()
		return err
	}
	return nil
}

type Note map[string]string

type LiteDB struct {
	db *sql.DB
}

func NewLiteDB(path string) (*LiteDB, error) {
	sql.Register("sqlite3_custom", &sqlite3.SQLiteDriver{
		ConnectHook: func(conn *sqlite3.SQLiteConn) error {
			return conn.RegisterFunc("utflower", utfLower, true)
		},
	})

	db, err := sql.Open("sqlite3_custom", path)
	litedb := LiteDB{db}
	return &litedb, errors.WithStack(err)
}

func utfLower(s string) string {
	return strings.ToLower(s)
}

func NewBearDB() (*LiteDB, error) {
	path := comp.Expanduser(DbPath)
	litedb, err := NewLiteDB(path)
	return litedb, err
}

func (litedb LiteDB) Query(q string, args ...interface{}) ([]Note, error) {
	results := []Note{}
	err := initBearDBIfNil()
	if err != nil {
		return results, err
	}

	rows, err := litedb.db.Query(q, args...)
	if err != nil {
		return results, errors.WithStack(err)
	}

	cols, err := rows.Columns()
	if err != nil {
		return results, errors.WithStack(err)
	}

	for rows.Next() {
		m := Note{}
		columns := make([]interface{}, len(cols))
		columnPointers := make([]interface{}, len(cols))
		for i := range columns {
			columnPointers[i] = &columns[i]
		}
		if err := rows.Scan(columnPointers...); err != nil {
			return results, errors.WithStack(err)
		}
		for i, colName := range cols {
			val := columnPointers[i].(*interface{})
			s, ok := (*val).(string)
			if ok {
				m[colName] = s
			} else {
				m[colName] = ""
			}
		}
		results = append(results, m)
	}
	err = rows.Close()
	if err != nil {
		return results, errors.WithStack(err)
	}
	err = rows.Err()
	if err != nil {
		return results, errors.WithStack(err)
	}
	return results, errors.WithStack(err)
}

func escape(s string) string {
	return strings.Replace(s, "'", "''", -1)
}

func (litedb LiteDB) NoteByTitle(title string) ([]Note, error) {
	title = escape(title)
	notes, err := litedb.Query(NOTE_BY_TITLE, title)
	return notes, err
}

// NoteByTitle returns best match note to title string.
func NoteByTitle(title string) (Note, error) {
	err := initBearDBIfNil()
	if err != nil {
		return nil, err
	}
	notes, err := bearDB.NoteByTitle(title)
	if err != nil {
		return nil, err
	}
	if len(notes) == 0 {
		return nil, nil
	}
	return notes[0], nil
}

// NoteIDByTitle returns best match note ID to title string.
func NoteIDByTitle(title string) (string, error) {
	note, err := NoteByTitle(title)
	if err != nil {
		return "", err
	}
	if note == nil {
		return "", nil
	}
	return note[NoteIDKey], nil
}

// NoteExistsByTitle returns true if a best match note ID to title string
// exists.
func NoteExistsByTitle(title string) (bool, error) {
	id, err := NoteIDByTitle(title)
	return id != "", err
}
```
